# Generated by Django 5.0 on 2024-12-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="product_images")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("email", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "globalStoreApp_customer",
            },
        ),
        migrations.CreateModel(
            name="DeliveryPartner",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("phone_number", models.CharField(default=0, max_length=20)),
                ("email", models.CharField(blank=True, max_length=100)),
                ("aadhaar", models.IntegerField(default=0, max_length=12)),
                ("bike", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="product_images")),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MainCategory",
                "verbose_name_plural": "MainCategories",
            },
        ),
        migrations.CreateModel(
            name="OtpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=10)),
                ("otp", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("whatsapp_number", models.CharField(max_length=20)),
                ("profile_image", models.CharField(max_length=100)),
                ("role_id", models.CharField(max_length=10)),
                ("social_login_type", models.CharField(max_length=10)),
                ("social_login_id", models.CharField(max_length=100)),
                ("is_phone_number_verified", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("aadhaar_number", models.CharField(max_length=12)),
                ("aadhaar_front", models.ImageField(blank=True, upload_to="")),
                ("aadhaar_back", models.ImageField(blank=True, upload_to="")),
                ("is_aadhar_verified", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=False)),
                ("fcm_token", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_type", models.CharField(max_length=10)),
                ("full_address", models.CharField(max_length=200)),
                ("house_no", models.CharField(blank=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("landmark", models.CharField(blank=True, max_length=100)),
                ("instruction", models.CharField(blank=True, max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="product_images")),
                ("description", models.TextField()),
                (
                    "main_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="globalStoreApp.maincategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("store_name", models.CharField(max_length=100)),
                ("store_slug", models.SlugField(max_length=100)),
                ("business_owner_name", models.CharField(max_length=100)),
                ("store_mobile", models.CharField(blank=True, max_length=20)),
                ("store_email", models.CharField(blank=True, max_length=100)),
                ("store_logo", models.ImageField(upload_to="")),
                ("store_banner", models.ImageField(upload_to="")),
                ("store_story", models.CharField(max_length=100)),
                ("store_type", models.CharField(max_length=100)),
                ("gst_number", models.CharField(blank=True, max_length=12)),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                ("store_description", models.CharField(max_length=100)),
                ("service_type", models.CharField(max_length=10)),
                ("categories", models.CharField(max_length=100)),
                ("store_code", models.CharField(max_length=100)),
                ("store_code_text", models.CharField(max_length=100)),
                ("loyalty_points", models.CharField(max_length=10)),
                ("store_address", models.CharField(max_length=100)),
                ("store_building", models.CharField(blank=True, max_length=100)),
                ("store_floor", models.CharField(blank=True, max_length=100)),
                ("store_tower", models.CharField(blank=True, max_length=100)),
                ("store_landmark", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("store_how_to_reach", models.CharField(blank=True, max_length=100)),
                ("store_country", models.CharField(max_length=100)),
                ("store_state", models.CharField(max_length=100)),
                ("store_city", models.CharField(max_length=100)),
                ("lat", models.CharField(max_length=10)),
                ("lng", models.CharField(max_length=10)),
                ("subscription_plan_id", models.CharField(max_length=10)),
                ("store_visibility", models.CharField(max_length=10)),
                ("store_status", models.CharField(max_length=10)),
                ("store_privacy_policy", models.CharField(max_length=100)),
                ("store_tnc", models.CharField(max_length=100)),
                ("store_refund_policy", models.CharField(max_length=100)),
                ("is_pickup", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "seller_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("highlight", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="product_images")),
                ("price", models.FloatField()),
                ("discountedPrice", models.FloatField(blank=True, null=True)),
                ("origin", models.TextField(blank=True)),
                ("tips", models.TextField(blank=True)),
                ("additional_info", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.category",
                    ),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.maincategory",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.store",
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, null=True, to="globalStoreApp.tags"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveSmallIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=10)),
                ("status", models.IntegerField(blank=True, default=0)),
                ("statusName", models.CharField(blank=True, max_length=100)),
                ("tip", models.FloatField(blank=True, default=0, max_length=9)),
                ("address_type", models.CharField(blank=True, max_length=10)),
                ("address_title", models.CharField(blank=True, max_length=100)),
                ("full_address", models.CharField(blank=True, max_length=200)),
                ("house_no", models.CharField(blank=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("landmark", models.CharField(blank=True, max_length=100)),
                ("instruction", models.CharField(blank=True, max_length=200)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.customer",
                    ),
                ),
                (
                    "deliveryPartner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="globalStoreApp.deliverypartner",
                    ),
                ),
                (
                    "orderItem",
                    models.ManyToManyField(null=True, to="globalStoreApp.orderitem"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                ("priority", models.SmallIntegerField(default=0)),
                ("startColor", models.CharField(max_length=10, null=True)),
                ("endColor", models.CharField(max_length=100, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.category",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="product_images")),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="globalStoreApp.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="globalStoreApp.variant",
            ),
        ),
        migrations.CreateModel(
            name="FestivalOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                ("priority", models.SmallIntegerField()),
                ("variant", models.ManyToManyField(to="globalStoreApp.variant")),
            ],
        ),
        migrations.CreateModel(
            name="FeatureListModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("highlight", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="product_images")),
                ("priority", models.IntegerField(blank=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.category",
                    ),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.maincategory",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalStoreApp.variant",
                    ),
                ),
            ],
        ),
    ]
