# Generated by Django 5.0 on 2025-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelReason",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
