# Generated by Django 5.0 on 2024-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypartner",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
