# Generated by Django 5.2.4 on 2025-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globalStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="description",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="heading",
            new_name="title",
        ),
        migrations.AddField(
            model_name="customer",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
