# Generated by Django 5.1.6 on 2025-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globalStoreApp", "0002_alter_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="imageMain",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.TextField(blank=True),
        ),
    ]
