# Generated by Django 5.0 on 2024-12-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0002_alter_deliverypartner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypartner",
            name="aadhaar",
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="deliveryPartner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="globalStoreApp.deliverypartner",
            ),
        ),
    ]
