# Generated by Django 5.1.6 on 2025-02-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globalStoreApp", "0002_order_cancelreason"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="pending_amount",
            field=models.FloatField(default=0),
        ),
    ]
