# Generated by Django 5.2 on 2025-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0002_product_imagemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.TextField(blank=True),
        ),
    ]
