# Generated by Django 5.1.1 on 2024-09-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0002_remove_tags_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='description',
        ),
    ]
