# Generated by Django 5.0 on 2024-12-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0002_wallet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="orderId",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="type",
        ),
        migrations.AddField(
            model_name="wallet",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="globalStoreApp.customer",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("remark", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="globalStoreApp.customer",
                    ),
                ),
                (
                    "orderId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="globalStoreApp.order",
                    ),
                ),
            ],
        ),
    ]
