# Generated by Django 5.2 on 2025-04-16 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qauntity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='aadhaar',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar number must be 12 digits.')]),
        ),
    ]
