# Generated by Django 5.0 on 2024-12-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0003_alter_deliverypartner_aadhaar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
