# Generated by Django 5.2 on 2025-04-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0003_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageMain',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
