# Generated by Django 5.0 on 2024-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0003_remove_wallet_orderid_remove_wallet_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Credit"), (1, "Debit"), (2, "withdraw request")]
            ),
        ),
    ]
