# Generated by Django 5.2 on 2025-04-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0003_product_qauntity_product_stock_product_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
