# Generated by Django 5.0 on 2024-12-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0004_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="amount",
            field=models.FloatField(),
        ),
    ]
