# Generated by Django 5.0 on 2024-12-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="statusName",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
