# Generated by Django 5.2 on 2025-04-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0004_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderItem',
            field=models.ManyToManyField(to='globalStoreApp.orderitem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='globalStoreApp.tags'),
        ),
    ]
