# Generated by Django 5.0 on 2024-12-29 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0005_alter_transaction_amount_alter_wallet_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="amount",
            new_name="balance",
        ),
    ]
