# Generated by Django 5.0 on 2024-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0005_order_statusname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
