# Generated by Django 5.2 on 2025-04-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0005_alter_order_orderitem_alter_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qauntity',
            new_name='qty',
        ),
    ]
