# Generated by Django 5.1.1 on 2024-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0005_alter_category_options_alter_maincategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
