# Generated by Django 5.0 on 2025-03-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0006_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="story",
            name="longitude",
            field=models.FloatField(default=0),
        ),
    ]
