# Generated by Django 5.0 on 2024-12-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0006_alter_seller_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="aadhaar_back",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="seller",
            name="aadhaar_front",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
