# Generated by Django 5.2 on 2025-07-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
