# Generated by Django 5.0 on 2025-01-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0006_rename_amount_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypartner",
            name="aadhaar",
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="deliverypartner",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
