# Generated by Django 5.0 on 2025-01-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0007_alter_deliverypartner_aadhaar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypartner",
            name="aadhaar",
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="deliverypartner",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
