# Generated by Django 5.0 on 2024-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0007_seller_aadhaar_back_seller_aadhaar_front"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="business_name",
            new_name="business_owner_name",
        ),
        migrations.AddField(
            model_name="store",
            name="store_email",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="store_mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
