# Generated by Django 5.0 on 2024-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "globalStoreApp",
            "0008_rename_business_name_store_business_owner_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="store_slug",
            field=models.SlugField(max_length=100),
        ),
    ]
