# Generated by Django 5.0 on 2025-01-30 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0008_alter_deliverypartner_aadhaar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="seller_id",
        ),
    ]
