# Generated by Django 5.0 on 2024-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalStoreApp", "0009_alter_store_store_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="gst_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="store",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
