# Generated by Django 5.1.1 on 2024-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0010_alter_product_brand_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tips',
            field=models.TextField(blank=True),
        ),
    ]
