# Generated by Django 5.1.1 on 2024-09-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0011_alter_product_additional_info_alter_product_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalStoreApp.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discountedPrice',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalStoreApp.tags'),
        ),
    ]
