# Generated by Django 5.1.1 on 2024-09-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0012_alter_product_brand_alter_product_discountedprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountedPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
