# Generated by Django 5.1.1 on 2024-09-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0018_alter_featurelistmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurelistmodel',
            name='tag',
        ),
    ]
