# Generated by Django 5.1.1 on 2024-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0019_remove_featurelistmodel_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelistmodel',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
