# Generated by Django 5.1.1 on 2024-09-25 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0020_featurelistmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalStoreApp.store'),
        ),
        migrations.AlterField(
            model_name='featurelistmodel',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
