# Generated by Django 5.1.1 on 2024-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0029_order_address_title_order_address_type_order_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip',
            field=models.FloatField(blank=True, default=0, max_length=9),
        ),
    ]
