# Generated by Django 5.1.1 on 2024-10-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0031_bannner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bannner',
            new_name='Banner',
        ),
    ]
