# Generated by Django 5.1.2 on 2024-10-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0033_festivaloffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festivaloffer',
            old_name='category',
            new_name='variant',
        ),
    ]
