# Generated by Django 5.1.2 on 2024-10-22 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0034_rename_category_festivaloffer_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalStoreApp.store'),
        ),
    ]
