# Generated by Django 5.1.2 on 2024-10-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0035_banner_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
