# Generated by Django 5.1.2 on 2024-10-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0038_deliverypartner_order_deliverypartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='bike',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
