# Generated by Django 5.1.2 on 2024-10-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalStoreApp', '0039_alter_deliverypartner_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
