# Generated by Django 5.1.6 on 2025-03-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
