# Generated by Django 5.2.1 on 2025-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WheelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.SmallIntegerField()),
                ("addressFrom", models.CharField(max_length=200)),
                ("latitudeFrom", models.FloatField()),
                ("longitudeFrom", models.FloatField()),
                ("addressTo", models.CharField(max_length=200)),
                ("latitudeTo", models.FloatField()),
                ("longitudeTo", models.FloatField()),
                ("vehicle", models.CharField(max_length=20)),
                ("price", models.FloatField(null=True)),
                ("distance", models.FloatField(null=True)),
                ("time", models.CharField(blank=True, max_length=20)),
                ("driver", models.SmallIntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("polylineRide", models.TextField(blank=True)),
                ("polylineDriver", models.TextField(blank=True)),
            ],
        ),
    ]
