# Generated by Django 5.1.2 on 2024-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.SmallIntegerField(max_length=8)),
                ('addressFrom', models.CharField(max_length=200)),
                ('latitudeFrom', models.FloatField()),
                ('longitudeFrom', models.FloatField()),
                ('addressTo', models.CharField(max_length=200)),
                ('latitudeTo', models.FloatField()),
                ('longitudeTo', models.FloatField()),
                ('vehicle', models.CharField(max_length=20)),
                ('driver', models.SmallIntegerField(max_length=8)),
                ('status', models.CharField(max_length=20)),
                ('polylineRide', models.TextField()),
                ('polylineDriver', models.TextField()),
            ],
        ),
    ]
