# Generated by Django 5.1.2 on 2024-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWheel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelbooking',
            name='customer',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='wheelbooking',
            name='driver',
            field=models.SmallIntegerField(),
        ),
    ]
