# Generated by Django 5.1.2 on 2024-10-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWheel', '0002_alter_wheelbooking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelbooking',
            name='driver',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='wheelbooking',
            name='polylineDriver',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wheelbooking',
            name='polylineRide',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wheelbooking',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
