# Generated by Django 5.1.2 on 2024-10-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWheel', '0004_alter_wheelbooking_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelbooking',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wheelbooking',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wheelbooking',
            name='time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
