# Generated by Django 5.2.1 on 2025-07-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatingNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dating.usermodel",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
