# Generated by Django 5.2.1 on 2025-06-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserDating",
        ),
    ]
