# Generated by Django 5.2.1 on 2025-07-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="image",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="text",
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dating.usermodel",
            ),
        ),
    ]
