# Generated by Django 5.2.4 on 2025-07-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="date_preference",
        ),
    ]
