# Generated by Django 5.2.4 on 2025-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read_by_receiver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_read_by_sender",
            field=models.BooleanField(default=False),
        ),
    ]
