# Generated by Django 5.2.1 on 2025-07-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AiMatch",
        ),
    ]
