# Generated by Django 5.2.4 on 2025-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0002_aimatch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="is_read",
            new_name="is_read_receiver",
        ),
        migrations.AddField(
            model_name="message",
            name="is_read_sender",
            field=models.BooleanField(default=False),
        ),
    ]
