# Generated by Django 5.2.4 on 2025-07-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0002_alter_usermodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="date_preference",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
