# Generated by Django 5.2.1 on 2025-06-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0002_rename_user_userdating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserDating",
            new_name="UserModel",
        ),
    ]
