# Generated by Django 5.2.1 on 2025-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0002_datingnotification_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="datingnotification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="datingnotification",
            name="is_read",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="datingnotification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
