# Generated by Django 5.2.1 on 2025-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0003_datingnotification_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
