# Generated by Django 5.2.4 on 2025-07-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0003_rename_is_read_message_is_read_receiver_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="is_read_receiver",
            new_name="is_read",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read_sender",
        ),
    ]
