# Generated by Django 5.2.1 on 2025-07-04 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0003_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="likedating",
            name="Message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="likedating",
            name="gift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dating.gift",
            ),
        ),
    ]
