# Generated by Django 5.2.1 on 2025-07-10 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0004_usermodel_fcm_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimatch",
            name="user1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_matches_as_user1",
                to="dating.usermodel",
            ),
        ),
        migrations.AlterField(
            model_name="aimatch",
            name="user2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_matches_as_user2",
                to="dating.usermodel",
            ),
        ),
    ]
