# Generated by Django 5.2.1 on 2025-07-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0004_likedating_message_likedating_gift"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likedating",
            old_name="Message",
            new_name="message",
        ),
    ]
