# Generated by Django 5.2.1 on 2025-06-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0004_datinguser"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatingToken",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to="dating.datinguser",
                    ),
                ),
            ],
        ),
    ]
