# Generated by Django 5.2.1 on 2025-06-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0005_datingtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="drink",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="drugs",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="marijuana",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="smoke",
            field=models.BooleanField(default=False),
        ),
    ]
