# Generated by Django 5.2.1 on 2025-07-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0006_aimatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimatch",
            name="message",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
