# Generated by Django 5.2.1 on 2025-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0006_alter_usermodel_drink_alter_usermodel_drugs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
