# Generated by Django 5.2.1 on 2025-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0007_alter_aimatch_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimatch",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
