# Generated by Django 5.2.1 on 2025-06-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0007_alter_usermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
