# Generated by Django 5.2.1 on 2025-06-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0008_alter_usermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
