# Generated by Django 5.2.1 on 2025-06-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0009_alter_usermodel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="id",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="dating.datinguser",
            ),
        ),
    ]
