# Generated by Django 5.2.1 on 2025-06-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0010_remove_usermodel_id_usermodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dating.datinguser",
            ),
        ),
    ]
