# Generated by Django 5.2.1 on 2025-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0011_usermodel_id_alter_usermodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="collageUniversity",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="education_level",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="ethnicity",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="home_town",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="job_title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="language",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="relation_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="work",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="zoodiac_sign",
            field=models.CharField(max_length=100),
        ),
    ]
