# Generated by Django 5.2.1 on 2025-06-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0012_alter_usermodel_collageuniversity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="zoodiac_sign",
            new_name="zodiac_sign",
        ),
    ]
