# Generated by Django 5.2.1 on 2025-06-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0013_rename_zoodiac_sign_usermodel_zodiac_sign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="drink",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="drugs",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="marijuana",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="smoke",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
