# Generated by Django 5.2.1 on 2025-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0014_alter_usermodel_drink_alter_usermodel_drugs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="likes",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
