# Generated by Django 5.2.1 on 2025-06-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0017_remove_like_image_remove_like_text_like_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Like",
            new_name="LikeDating",
        ),
    ]
