# Generated by Django 5.2.1 on 2025-06-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0018_rename_like_likedating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="image",
        ),
        migrations.RemoveField(
            model_name="match",
            name="text",
        ),
        migrations.AddField(
            model_name="match",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_received",
                to="dating.usermodel",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_sent",
                to="dating.usermodel",
            ),
        ),
    ]
