# Generated by Django 5.2.1 on 2025-06-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0019_remove_match_image_remove_match_text_match_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="image",
        ),
        migrations.AddField(
            model_name="message",
            name="date_sent",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_received",
                to="dating.usermodel",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_sent",
                to="dating.usermodel",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
