# Generated by Django 5.2.1 on 2025-06-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0020_remove_message_image_message_date_sent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                (
                    "user_standout",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dating.usermodel",
                    ),
                ),
            ],
        ),
    ]
