# Generated by Django 5.2.1 on 2025-06-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0021_standout"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsoredOuting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("outing_type", models.CharField(max_length=100, null=True)),
                ("location", models.CharField(max_length=200, null=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("outing_date", models.DateTimeField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_sponsored",
                        to="dating.usermodel",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_sponsored",
                        to="dating.usermodel",
                    ),
                ),
            ],
        ),
    ]
