# Generated by Django 5.2.1 on 2025-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0022_sponsoredouting"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsoredouting",
            name="avenue_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sponsoredouting",
            name="from_time",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sponsoredouting",
            name="otp",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="sponsoredouting",
            name="outing_status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sponsoredouting",
            name="payment_status",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="sponsoredouting",
            name="to_time",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
