# Generated by Django 5.2.1 on 2025-07-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0023_sponsoredouting_avenue_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="sponsoredouting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
