# Generated by Django 5.2.1 on 2025-07-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0024_gift_alter_sponsoredouting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsoredouting",
            name="payment_status",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
