# Generated by Django 5.2.1 on 2025-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0025_alter_sponsoredouting_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
